language: python
python:
  - "3.8"

branches:
  only:
    - master

# Start services.
services:
  - docker-compose

before_install:
- docker-compose up

# command to install dependencies.
install: "pip install -r requirements.txt"

before_script:
  - cp .env.example .env
script:
  - docker-compose exec web python manage.py migrate
sudo: false
