# Generated by Django 3.1.7 on 2021-02-22 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20210222_2317'),
        ('assets', '0002_auto_20210222_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsmodel',
            name='person',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='people.peoplemodel'),
        ),
    ]
