# Generated by Django 3.1.7 on 2021-02-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplemodel',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='peoplemodel',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='peoplemodel',
            name='email',
            field=models.EmailField(max_length=150, unique=True, verbose_name='E-mail'),
        ),
    ]
