# Generated by Django 3.1.7 on 2021-02-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20210221_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplemodel',
            name='owners',
            field=models.ManyToManyField(related_name='_peoplemodel_owners_+', to='people.PeopleModel'),
        ),
    ]
