# Generated by Django 3.1.7 on 2021-02-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_peoplemodel_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplemodel',
            name='owners',
            field=models.ManyToManyField(blank=True, null=True, related_name='_peoplemodel_owners_+', to='people.PeopleModel'),
        ),
    ]
