# Generated by Django 3.1.7 on 2021-02-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20210221_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplemodel',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='subordinates', to='people.PeopleModel'),
        ),
    ]
