# Generated by Django 3.1.7 on 2021-02-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20210221_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplemodel',
            name='people_type',
            field=models.CharField(choices=[('F', 'FISICA'), ('J', 'JURIDICA')], max_length=1, verbose_name='Tipo de Pessoa'),
        ),
    ]
